import math

CURVE_COUNT_PER_10x10 = 2
MAX_ENDPIXEL_DEVIATION = 0.095
MAX_WIDTH_DEVIATION = 4
BASE_WIDTH = 5
THREADS_COUNT = 2


# CURVE_COUNT_PER_10x10 = 14
# MAX_ENDPIXEL_DEVIATION = 0.015
# MAX_WIDTH_DEVIATION = 4
# BASE_WIDTH = 6
# THREADS_COUNT = 2